MiniMercadoVirtual/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MiniMercadoVirtual.Models.Enums;

namespace MiniMercadoVirtual.Models
{
    public class Cliente
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Campo nome é um campo obrigatório.")]
        public string Nome { get; set; }
        [Display(Name ="E-mail")]
        [Required(ErrorMessage = "Campo e-mail é um campo obrigatório.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Campo senha é um campo obrigatório.")]
        public string Senha { get; set; }
        public List<Endereco> Endereco { get; set; }
        [Display(Name ="Data de Cadastro")]
        public DateTime DtInclusao { get; set; }
        [Display(Name = "Data de Atualização")]
        public DateTime DtAlteracao { get; set; }
        public  StatusCliente Status { get; set; }
        public List<Pedido> Pedidos { get; set; }
    }
}

MiniMercadoVirtual/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiniMercadoVirtual.Services;
using MiniMercadoVirtual.Models;
using MiniMercadoVirtual.Models.ViewModels;

namespace MiniMercadoVirtual.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IClientesService _iclientesService;
        private readonly IEnderecosService _ienderecosService;
        public ClientesController(IClientesService iclientesService, IEnderecosService enderecosService)
        {
            _iclientesService = iclientesService;
            _ienderecosService = enderecosService;
        }

        // GET: Clientes
        public IActionResult Index()
        {
            var ClientesDomain = _iclientesService.BuscarTodos();
            List<Cliente> Clientes = new List<Cliente>();
            foreach (var item in ClientesDomain)
            {
                Cliente Cliente = new Cliente
                {
                    Id = item.Id,
                    Nome = item.Nome,
                    Email = item.Email,
                    Senha = item.Senha,
                    Status = (Models.Enums.StatusCliente)item.Status
                };
                Clientes.Add(Cliente);
            }
            return View(Clientes);
        }

        // GET: Clientes/Details
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ClienteDomain = _iclientesService.BuscarPorId(id.Value);
            Cliente Cliente = new Cliente();
            if (ClienteDomain == null)
            {
                return NotFound();
            }
            else
            {
                Cliente.Id = ClienteDomain.Id;
                Cliente.Nome = ClienteDomain.Nome;
                Cliente.Email = ClienteDomain.Email;
                Cliente.Senha = ClienteDomain.Senha;
                Cliente.DtInclusao = ClienteDomain.DtInclusao;
                Cliente.DtAlteracao = ClienteDomain.DtAlteracao;
                Cliente.Status = (Models.Enums.StatusCliente)ClienteDomain.Status;
            }
            var EnderecosDomain = _ienderecosService.BuscarPorCliente(Cliente.Id);
            List<Endereco> enderecos = new List<Endereco>();
            if (EnderecosDomain != null)
            {
                foreach (var item in EnderecosDomain)
                {
                    Endereco endereco = new Endereco
                    {
                        Id = item.Id,
                        Cep = item.Cep,
                        Logradouro = item.Logradouro,
                        Numero = item.Numero,
                        Bairro = item.Bairro,
                        Cidade = item.Cidade,
                        Uf = item.Uf,
                        Complemento = item.Complemento,
                        ClienteId = item.ClienteId
                    };
                    enderecos.Add(endereco);
                }
            }
            Cliente.Endereco = enderecos;
            return View(Cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cliente Cliente)
        {
            if (ModelState.IsValid)
            {
                Domain.Cliente ClienteDomain = new Domain.Cliente
                {
                    Nome = Cliente.Nome,
                    Email = Cliente.Email,
                    Senha = Cliente.Senha,
                    Status = (Domain.Enums.StatusCliente)Cliente.Status
                };
                _iclientesService.Cadastrar(ClienteDomain);
                return RedirectToAction(nameof(Index));
            }
            return View(Cliente);
        }

        // GET: Clientes/Edit
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ClienteDomain = _iclientesService.BuscarPorId(id.Value);
            if (ClienteDomain == null)
            {
                return NotFound();
            }
            Cliente Cliente = new Cliente
            {
                Id = ClienteDomain.Id,
                DtInclusao = ClienteDomain.DtInclusao,
                Nome = ClienteDomain.Nome,
                Senha = ClienteDomain.Senha,
                Email = ClienteDomain.Email,
                Status = (Models.Enums.StatusCliente)ClienteDomain.Status
            };
            return View(Cliente);
        }


        // POST: Clientes/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Cliente Cliente)
        {
            if (ModelState.IsValid)
            {
                Domain.Cliente ClienteDomain = new Domain.Cliente
                {
                    Id = Cliente.Id,
                    DtInclusao = Cliente.DtInclusao,
                    Nome = Cliente.Nome,
                    Email = Cliente.Email,
                    Senha = Cliente.Senha,
                    Status = (Domain.Enums.StatusCliente)Cliente.Status
                };
                _iclientesService.Alterar(ClienteDomain);
                return RedirectToAction(nameof(Index));
            }
            return View(Cliente);
        }

        // GET: Clientes/Delete
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var clienteDomain = _iclientesService.BuscarPorId(id.Value);
            if (clienteDomain == null)
            {
                return NotFound();
            }
            Cliente cliente = new Cliente
            {
                Id = clienteDomain.Id,
                Nome = clienteDomain.Nome,
                Email = clienteDomain.Email,
                Senha = clienteDomain.Senha,
                DtInclusao = clienteDomain.DtInclusao,
                DtAlteracao = clienteDomain.DtAlteracao,
                Status = (Models.Enums.StatusCliente)clienteDomain.Status
            };
            return View(cliente);
        }

        // POST: Clientes/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var cliente = _iclientesService.BuscarPorId(id);
            if(cliente == null)
            {
                return NotFound();
            }
            _iclientesService.Remover(cliente);
            return RedirectToAction(nameof(Index));
        }
    }
}

MiniMercadoVirtual/Controllers/EnderecosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniMercadoVirtual.Services;
using MiniMercadoVirtual.Models;
using MiniMercadoVirtual.Models.ViewModels;


namespace MiniMercadoVirtual.Controllers
{ 
    public class EnderecosController : Controller
    {
        private readonly IClientesService _iclientesService;
        private readonly IEnderecosService _ienderecosService;
        public EnderecosController(IClientesService iclientesService, IEnderecosService enderecosService)
        {
            _iclientesService = iclientesService;
            _ienderecosService = enderecosService;
        }
        public IActionResult Index()
        {
            var ClienteDomain = _iclientesService.BuscarTodos();
            List<Cliente> Clientes = new List<Cliente>();
            if (ClienteDomain != null)
            {
                foreach (var item in ClienteDomain)
                {
                    Cliente cliente = new Cliente
                    {
                        Nome = item.Nome
                    };
                    if (item.Endereco != null)
                    {
                        List<Endereco> enderecos = new List<Endereco>();
                        foreach (var end in item.Endereco)
                        {
                            Endereco endereco = new Endereco
                            {
                                Id = end.Id,
                                Cep = end.Cep,
                                Logradouro = end.Logradouro,
                                Numero = end.Numero,
                                Bairro = end.Bairro,
                                Cidade = end.Cidade,
                                Uf = end.Uf,
                                Complemento = end.Complemento
                            };
                            enderecos.Add(endereco);
                        }
                        cliente.Endereco = enderecos;
                    }
                    Clientes.Add(cliente);
                }
            }
            return View(Clientes);
        }

        //GET Endereco/Cadastrar
        public IActionResult Cadastrar()
        {
            var clientesDomain = _iclientesService.BuscarTodos();
            List<Cliente> clientes = new List<Cliente>();
            foreach (var item in clientesDomain)
            {
                Cliente cliente = new Cliente
                {
                    Id = item.Id,
                    Nome = item.Nome
                };
                clientes.Add(cliente);
            }
            var ViewModel = new EnderecoFormViewModel { Clientes = clientes };
            return View(ViewModel);
        }

        //POST: Endereco/Cadastrar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Criar(Endereco endereco)
        {
            Domain.Endereco enderecoDomain = new Domain.Endereco
            {
                Cep = endereco.Cep,
                Logradouro = endereco.Logradouro,
                Numero = endereco.Numero,
                Bairro = endereco.Bairro,
                Cidade = endereco.Cidade,
                Uf = endereco.Uf,
                Complemento = endereco.Complemento,
                ClienteId = endereco.ClienteId
            };
            _ienderecosService.Criar(enderecoDomain);
            return RedirectToAction(nameof(Index));
        }
        //GET Endereco/Alterar
        public IActionResult Alterar(int id)
        {
            var enderecoDomain = _ienderecosService.BuscarPorId(id);
            if (enderecoDomain == null)
            {
                return NotFound();
            }
            Endereco endereco = new Endereco
            { 
                Id = enderecoDomain.Id,
                Cep = enderecoDomain.Cep,
                Logradouro = enderecoDomain.Logradouro,
                Numero = enderecoDomain.Numero,
                Bairro = enderecoDomain.Bairro,
                Cidade = enderecoDomain.Cidade,
                Uf = enderecoDomain.Uf,
                Complemento = enderecoDomain.Complemento,
                ClienteId = enderecoDomain.ClienteId
            };

            var clientesDomain = _iclientesService.BuscarTodos();
            List<Cliente> clientes = new List<Cliente>();
            foreach(var item in clientesDomain)
            {
                Cliente cliente = new Cliente
                {
                    Id = item.Id,
                    Nome = item.Nome
                };
                clientes.Add(cliente);
            }
            var ViewModel = new EnderecoFormViewModel { Endereco = endereco,Clientes =  clientes };
            return View(ViewModel);
        }

        //POST: Endereco/Alterar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Atualizar(Endereco endereco)
        {
            Domain.Endereco enderecoDomain = new Domain.Endereco
            {
                Id = endereco.Id,
                Cep = endereco.Cep,
                Logradouro = endereco.Logradouro,
                Numero = endereco.Numero,
                Bairro = endereco.Bairro,
                Cidade = endereco.Cidade,
                Uf = endereco.Uf,
                Complemento = endereco.Complemento,
                ClienteId = endereco.ClienteId
            };
            _ienderecosService.Atualizar(enderecoDomain);
            return RedirectToAction(nameof(Index));
        }
        
        //GET: Endereco/Excluir
        public IActionResult Excluir(int id)
        {
            var enderecoDomain = _ienderecosService.BuscarPorId(id);
            Endereco endereco = new Endereco
            {
                Id = enderecoDomain.Id,
                Cep = enderecoDomain.Cep,
                Logradouro = enderecoDomain.Logradouro,
                Numero = enderecoDomain.Numero,
                Bairro = enderecoDomain.Bairro,
                Cidade = enderecoDomain.Cidade,
                Uf = enderecoDomain.Uf,
                Complemento = enderecoDomain.Complemento,
                ClienteId = enderecoDomain.ClienteId
            };
            return View(endereco);
        }
        //POST: Endereco/Excluir
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmarExclusao(Endereco endereco)
        {
            Domain.Endereco enderecoDomain = new Domain.Endereco
            {
                Id = endereco.Id,
                Cep = endereco.Cep,
                Logradouro = endereco.Logradouro,
                Numero = endereco.Numero,
                Bairro = endereco.Bairro,
                Cidade = endereco.Cidade,
                Uf = endereco.Uf,
                Complemento = endereco.Complemento,
                ClienteId = endereco.ClienteId
            };
            _ienderecosService.Excluir(enderecoDomain);
            return RedirectToAction(nameof(Index));
        }
    }
}

MiniMercadoVirtual/Views/Clientes/Create.cshtml
@model MiniMercadoVirtual.Models.Cliente
@{
    ViewData["Title"] = "Cadastrar";
}

<p>
    <h3>Cadastrar</h3>
</p>
<h4>Cliente</h4>

    <div class="row">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Senha" class="control-label"></label>
                    <input asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Status" class="control-label"></label>
                    <select asp-for="Status" class="form-control">
                        <option value="1">Ativo</option>
                        <option value="2">Suspenso</option>
                        <option value="3">Desativado</option>
                    </select>
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Cadastrar" class="btn btn-success" /> - <a class="btn btn-primary" asp-action="Index">Lista de Clientes</a>
                </div>
            </div>
        </form>
    </div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

MiniMercadoVirtual/Views/Clientes/Delete.cshtml
@model MiniMercadoVirtual.Models.Cliente

@{
    ViewData["Title"] = "Excluir";
}

<p>
    <h3>Excluir</h3>
</p>
<h4>Cliente</h4>
<h3>Você tem certeza que deseja excluir esse cliente ?</h3>
<div class="row">
    <table class="table">
        <tr>
            <td class="col-md-2"><strong>@Html.DisplayNameFor(model => model.Nome)</strong></td>
            <td class="col-md-10">@Model.Nome</td>
        </tr>
        <tr>
            <td class="col-md-2"><strong>@Html.DisplayNameFor(model => model.Email)</strong></td>
            <td class="col-md-10">@Model.Email</td>
        </tr>
        <tr>
            <td class="col-md-2"><strong>@Html.DisplayNameFor(model => model.Senha)</strong></td>
            <td class="col-md-10">@Model.Senha</td>
        </tr>
        <tr>
            <td class="col-md-2"><strong>@Html.DisplayNameFor(model => model.DtInclusao)</strong></td>
            <td class="col-md-10">@Model.DtInclusao</td>
        </tr>
        <tr>
            <td class="col-md-2"><strong>@Html.DisplayNameFor(model => model.DtAlteracao)</strong></td>
            @if (Model.DtAlteracao == Convert.ToDateTime("01/01/0001 00:00:00"))
            {
                <td class="col-md-10"></td>
            }
            else
            {
                <td class="col-md-10">@Model.DtAlteracao</td>
            }
        </tr>
        <tr>
            <td class="col-md-2"><strong>@Html.DisplayNameFor(model => model.Status)</strong></td>
            <td class="col-md-10">@Model.Status</td>
        </tr>
    </table>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Confirmar" class="btn btn-danger" /> - <a class="btn btn-primary" asp-action="Index">Lista de Clientes</a>
    </form>
</div>

MiniMercadoVirtual/Views/Clientes/Details.cshtml
@model MiniMercadoVirtual.Models.Cliente

@{
    ViewData["Title"] = "Detalhes";
}

<p>
    <h3>Detalhes</h3>
</p>

<h4>Cliente</h4>
<div class="row">
    <table class="table">
        <tr>
            <td class="col-md-2"><strong>@Html.DisplayNameFor(model => model.Nome)</strong></td>
            <td class="col-md-10">@Model.Nome</td>
        </tr>
        <tr>
            <td><strong>@Html.DisplayNameFor(model => model.Email)</strong></td>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <td><strong>@Html.DisplayNameFor(model => model.Senha)</strong></td>
            <td>@Model.Senha</td>
        </tr>
        <tr>
            <td><strong>@Html.DisplayNameFor(model => model.DtInclusao)</strong></td>
            <td>@Model.DtInclusao</td>
        </tr>
        <tr>
            <td><strong>@Html.DisplayNameFor(model => model.DtAlteracao)</strong></td>
            @if (Model.DtAlteracao == Convert.ToDateTime("01/01/0001 00:00:00"))
            {
                <td></td>
            }
            else
            {
                <td>@Model.DtAlteracao</td>
            }
        </tr>
        <tr>
            <td><strong>@Html.DisplayNameFor(model => model.Status)</strong></td>
            <td>@Model.Status</td>
        </tr>
    </table>
</div>
<p><strong>Endereços</strong></p>
@if (Model.Endereco.Count != 0)
{
    <div>
        <table class="table col-md-12">
            <thead>
                <tr>
                    <th>Cep</th>
                    <th>Logradouro</th>
                    <th>Número</th>
                    <th>Bairro</th>
                    <th>Cidade</th>
                    <th>Uf</th>
                    <th>Complemento</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Endereco)
                {
                    <tr>
                        <td>@item.Cep</td>
                        <td>@item.Logradouro</td>
                        <td>@item.Numero</td>
                        <td>@item.Bairro</td>
                        <td>@item.Cidade</td>
                        <td>@item.Uf</td>
                        <td>@item.Complemento</td>
                        <td><a class="btn btn-primary btn-sm" asp-action="Alterar" asp-controller="Enderecos" asp-route-id="@item.Id">Editar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p>Cliente não possue endereços cadastrados.</p>
}
<div>
    <br /><a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Editar</a> - <a class="btn btn-primary" asp-action="Index">Lista de Clientes</a>
</div>

MiniMercadoVirtual/Views/Clientes/Edit.cshtml
@model MiniMercadoVirtual.Models.Cliente

@{
    ViewData["Title"] = "Editar";
}

<p>
    <h3>Editar</h3>
</p>
<h4>Cliente</h4>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DtInclusao" />

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="1">Ativo</option>
                    <option value="2">Suspenso</option>
                    <option value="3">Desativado</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success" /> - <a class="btn btn-primary" asp-action="Index">Lista de Clientes</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MiniMercadoVirtual/Views/Clientes/Index.cshtml
@model IEnumerable<MiniMercadoVirtual.Models.Cliente>

@{
    ViewData["Title"] = "Clientes";
}
<p>
    <h3>Clientes</h3>
</p>
<p>
    <a asp-action="Create" class="btn btn-primary">Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Senha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{
        <tr>
            <td>
                @item.Nome
            </td>
            <td>
                @item.Email
            </td>
            <td>
                @item.Senha
            </td>
            <td>
                @item.Status
            </td>
            <td>
                <a class="btn btn-primary btn-sm" asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a class="btn btn-primary btn-sm" asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>